
const client_id = process.env.SPOTIFY_CLIENT_ID;
const client_secret = process.env.SPOTIFY_CLIENT_SECRET;
const basic = Buffer.from(`${client_id}:${client_secret}`).toString('base64');
const TOKEN_ENDPOINT = `https://accounts.spotify.com/api/token`;

export const getAccessToken = async (refresh_token) => {
    const response = await fetch(TOKEN_ENDPOINT, {
        method: 'POST',
        headers: {
            Authorization: `Basic ${basic}`,
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: new URLSearchParams({
            grant_type: 'refresh_token',
            refresh_token,
        }),
    });

    return response.json();
};

export const exchangeCodeForToken = async (code, redirect_uri) => {
    const response = await fetch(TOKEN_ENDPOINT, {
        method: 'POST',
        headers: {
            Authorization: `Basic ${basic}`,
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: new URLSearchParams({
            grant_type: 'authorization_code',
            code,
            redirect_uri,
        }),
    });
    return response.json();
}

export const searchArtists = async (query, token) => {
    const response = await fetch(`https://api.spotify.com/v1/search?type=artist&q=${encodeURIComponent(query)}&limit=10`, {
        headers: {
            Authorization: `Bearer ${token}`
        }
    });
    return response.json();
};

export const searchTracks = async (query, token) => {
    const response = await fetch(`https://api.spotify.com/v1/search?type=track&q=${encodeURIComponent(query)}&limit=10`, {
        headers: {
            Authorization: `Bearer ${token}`
        }
    });
    return response.json();
};

export const getArtistTopTracks = async (artistId, token, market = 'US') => {
    const response = await fetch(`https://api.spotify.com/v1/artists/${artistId}/top-tracks?market=${market}`, {
        headers: {
            Authorization: `Bearer ${token}`
        }
    });
    return response.json();
};

export const getUserTopItems = async (type, token, time_range = 'medium_term', limit = 20) => {
    // type: 'artists' or 'tracks'
    const response = await fetch(`https://api.spotify.com/v1/me/top/${type}?time_range=${time_range}&limit=${limit}`, {
        headers: {
            Authorization: `Bearer ${token}`
        }
    });
    return response.json();
};

export const searchTracksByGenre = async (genre, token) => {
    const response = await fetch(`https://api.spotify.com/v1/search?type=track&q=genre:${encodeURIComponent(genre)}&limit=10`, {
        headers: {
            Authorization: `Bearer ${token}`
        }
    });
    return response.json();
};

export const getCurrentUser = async (token) => {
    const response = await fetch('https://api.spotify.com/v1/me', {
        headers: {
            Authorization: `Bearer ${token}`
        }
    });
    return response.json();
};

export const createPlaylist = async (userId, name, token) => {
    const response = await fetch(`https://api.spotify.com/v1/users/${userId}/playlists`, {
        method: 'POST',
        headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            name: name,
            description: 'Generated by Spotify Taste Mixer',
            public: false
        })
    });
    return response.json();
};

export const addTracksToPlaylist = async (playlistId, uris, token) => {
    await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, {
        method: 'POST',
        headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            uris: uris
        })
    });
};
